### ISSUE TITLE
Prune.vi only checks for logfiles with *.csv extension

### ISSUE THREAD

**Issue by fuzzy-focus** [fieldrndservices/logger#2]
If a custom extension (e.g. *.log) is used, old logfiles will never be deleted as they are not checked for.

**Comment by volks73** [comment]
Thank you for the bug report. I have been able to reproduce the problem and implemented a fix. I am in the process of pushing a update to the NI Tools Network, which will take some time. If you need the fix faster, let me know. I can send you a pre-release version of the VIP with the fix. The new version will be v1.9.0.

Thanks to your bug report, I also found some other issues. The new release includes these fixes along with a new feature related to pruning. I am in the process of pushing the changes to GitHub as well.

**Comment by fuzzy-focus** [comment]
> I can send you a pre-release version of the VIP with the fix.

That would be fantastic. You can also add binaries (like your VIP file) to tagged releases here on Github.  If you don't have an issue with that, I guess that would be the most practical solution.

**Comment by volks73** [comment]
I just got word that the updated VIP (v1.9.0) with this fix should appear on VIPM tomorrow (2019-08-06). So, it might just be easier to wait a day for the NI Tools Network repository to refresh and upgrade through VIPM.
