### ISSUE TITLE
Double quotes in the message text need to be escaped

### ISSUE THREAD

**Issue by fuzzy-focus** [fieldrndservices/logger#4]
If the message contains a double quote, it should be represented with a pair of double quotes as per the CSV standard.

'this is a "message" with quotes' ->'this is a ""message"" with quotes'

otherwise it is difficult to parse the CSV file.

**Comment by volks73** [comment]
Yes, good catch. According to [RFC 4180](https://tools.ietf.org/html/rfc4180):

>5. Each field may or may not be enclosed in double quotes...If fields are not enclosed with double quotes, then double quotes may not appear inside the fields...

>6. Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes...

>7. If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote...

The `Create Statement CSV`, or soon-to-be `Create Statement Line`, VI is used to create each line in the log file:

![Create-Statement-Lines-Snippet](https://user-images.githubusercontent.com/1915469/62477185-72b50280-b776-11e9-8b20-27da3931db28.png)

As seen in the above VI snippet, the `Message` field is surrounded by in double-quotes, regardless of its contents, to follow as closely as possible to RFC 4180 Item 6 from above, but it does _not_ inspect the contents for existing double quotes and escape them according to Item 7.

This appears to be an easy fix by using the [Search and Replace String](http://zone.ni.com/reference/en-XX/help/371361R-01/glang/search_and_replace_string/) function for double-quotes within the message and replace with two double quotes _before_ surrounding the `Message` field with double-quotes.

**Comment by volks73** [comment]
So, something like this should do the trick:

![Create-Statement-Lines-Escaped-Quotes-Snippet](https://user-images.githubusercontent.com/1915469/62477373-dc351100-b776-11e9-8805-b6f2c9129a1f.png)

I need to do some testing and add some other changes before pushing another new release to the VIPM repository.

**Comment by volks73** [comment]
Okay, escaping double-quotes has been added as of a9ae0b5fe7e76a2c26456aba4fa63ae138df9fa1

I still need to test this solution and finish the documentation, but functionality is available at the bleeding edge of the source code.
